# Generated by Django 4.1 on 2024-04-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="cutoff_val",
        ),
    ]
