# Generated by Django 4.1 on 2024-04-02 06:22

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_alter_upload_cutoff_val"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="image",
            field=models.ImageField(upload_to=uploads.models.custom_image_path),
        ),
    ]
