# Generated by Django 4.1 on 2024-04-02 08:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0005_alter_upload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="cutoff_val",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(300.0),
                ],
            ),
        ),
    ]
