# Generated by Django 4.1 on 2024-05-08 01:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0007_upload_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="processing_time",
            field=models.DecimalField(
                decimal_places=9, default=Decimal("0E-9"), max_digits=12
            ),
        ),
    ]
