# Generated by Django 4.1 on 2024-05-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0008_upload_processing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
