# Generated by Django 4.1 on 2024-05-08 09:27

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0010_alter_upload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="image",
            field=models.ImageField(upload_to=uploads.models.custom_image_path),
        ),
    ]
